### ISSUE TITLE
dashboard: Add filter for required tests

### ISSUE THREAD

**Issue by sprt** [kata-containers/kata-containers.github.io#2]
Acceptance criteria:
- [ ] Add a checkbox next to the search bar with label `Required` that only shows required tests when selected.
- [ ] In the table, required tests have a `required` badge appended, like in PR checks listings.

**Comment by afinn12** [comment]
Required tag is a column, not a badge. But is filterable/sortable.
(PR #7 in our repo) 

![Image](https://github.com/user-attachments/assets/06aa49ce-4245-420d-90f4-c53e42dbcaab)

**Comment by sprt** [comment]
Ready for review
