### ISSUE TITLE
dashboard: Add maintainers for each test

### ISSUE THREAD

**Issue by sprt** [kata-containers/kata-containers.github.io#5]
Acceptance criteria:
- [x] [@sprt] Create Github groups corresponding to maintainers for each test
   - We actually already have some GH groups, let's start with these:
     - @kata-containers/arch-s390x
     - @kata-containers/intel
     - @kata-containers/arch-ppc64le
     - @kata-containers/cri-o
     - @kata-containers/dragonball
     - @kata-containers/rust
- [ ] Create mapping of groups -> tests in dashboard repo
   - Use regexes to match a test name to a group (check with @sprt on crafting these regexes) 
- [ ] Implement showing maintainers for each test:
   - When a test is expanded, we show a link to the maintainers group(s)
   - Keep in mind multiple groups may be associated with a given test (if not already today, in the future)

**Comment by afinn12** [comment]
- Created initial mappings in maintainer.yml
- Basic implementation of maintainers list working
  - Tested in dev
  - Works for 0+ maintainers
  - Link takes them to the person's Github account

![Image](https://github.com/user-attachments/assets/a94932bb-02f3-4b75-b332-5a31a4b1b792)

**Comment by AdithyaKrishnan** [comment]
Could you please create a GH group for AMD please

**Comment by afinn12** [comment]
Unable to upload .yml so here's a link to the existing .yml file:
https://github.com/a1icja/kata-dashboard-next/blob/maintainers-list/maintainers.yml

**Comment by afinn12** [comment]
![image](https://github.com/user-attachments/assets/30e53036-efbc-4b21-a7d1-91a04f31a33a)

- Will list all maintainers if there's multiple regex matches.
- Should the groupings be indicated (i.e. Mores&Li = rust and Choi = arch-s390x)?
